### PR TITLE
Initial Setup Next.js Commerce & API connection with Shopify

### PR DESCRIPTION
**Pull request by alianza**
Next.js Commerce framework cloned
Shopify Api connection established
Display products on homepage

### CODE REVIEW

**Comment by pascalw** [comment]
@alianza Can you please squash all commits from the upstream Next.js Commerce repo into one? We don't need the history of that repo, as it clutters our own history. Here's a guide on how to do this: https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec.

**Comment by pascalw** [comment]
Few other things:

* Can you also please update the README to reflect how to get this up and running locally? Just some brief instructions like `yarn install`, copy `.env.template` to `.env`, run `yarn start` etc.
* Please add a `.tool-versions` file to configure which Node.js version should be used. This is a file used by tools like https://asdf-vm.com/. These tools are used to manage different Node.js, Python, Ruby etc versions across different projects.
* Can you update `.env.template`?

**Comment by alianza** [comment]
> @alianza Can you please squash all commits from the upstream Next.js Commerce repo into one? We don't need the history of that repo, as it clutters our own history. Here's a guide on how to do this: https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec.

Ik ga hier naar kijken!

**Comment by pascalw** [comment]
@egonm12 Jest setup is part of the next story to setup CI with GitHub actions.

**Comment by alianza** [comment]
> > @alianza Can you please squash all commits from the upstream Next.js Commerce repo into one? We don't need the history of that repo, as it clutters our own history. Here's a guide on how to do this: https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec.
> 
> Ik ga hier naar kijken!

@pascalw Om een of andere reden lukt het niet de commits te squashen. Ik ben dit nu al een tijdje aan het proberen. Ik zie wel dat de `merge pull request` button hier in het Github PR de optie heeft om de commits te squashen. Misschien werkt dat makkelijker?

**Comment by egonm12** [comment]
Can you also remove the `.vscode` folder and add it to the gitignore as well? I also saw that you didn't specify a path for eslint. When I ran `yarn eslint --fix .` I saw some errors and quite a few warnings.
If you want to ignore certain files or directories please add a `.eslintignore` file as well.

You can add this in your eslintrc.json to automatically detect the react version to fix that warning when you run eslint
```
"settings": {
        "react": {
            "version": "detect"
        }
    },
```

**Review by egonm12 — APPROVED** [review]

**Comment by pascalw** [comment]
FYI we discussed not to squash the Next commerce commits to make it easier to update Next commerce in the future. That could still lead to a lot of conflicts, but squashing everything would make it even harder.

**Pull request merged**
